USB_VID = 0x239A
USB_PID = 0x80A0
USB_PRODUCT = "BT60"
USB_MANUFACTURER = "Polarityworks"

MCU_CHIP = nrf52840

INTERNAL_FLASH_FILESYSTEM = 1
FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_BLE


#CIRCUITPY_DISPLAYIO = 0    # Nur benötigt, wenn ein Display verwendet wird
CIRCUITPY_AUDIOBUSIO = 0   # Nur benötigt für Audio
CIRCUITPY_AUDIOCORE = 0    # Nur benötigt für Audio
CIRCUITPY_AUDIOMIXER = 0   # Nur benötigt für Audio
CIRCUITPY_AUDIOMP3 = 0     # Nur benötigt für Audio
CIRCUITPY_AUDIOPWMIO = 0   # Nur benötigt für Audio
CIRCUITPY_ULAB = 0         # Nur benötigt für wissenschaftliche Berechnungen
#CIRCUITPY_SHARPDISPLAY = 0 # Nur benötigt für Sharp Displays
#CIRCUITPY_RGBMATRIX = 0    # Nur benötigt für RGB Matrix Displays
CIRCUITPY_PULSEIO = 0      # Nur benötigt für Pulserzeugung
#CIRCUITPY_PWMIO = 0        # Nur benötigt für PWM
#CIRCUITPY_ONEWIREIO = 0    # Nur benötigt für 1-Wire Protokoll
CIRCUITPY_I2CDISPLAYBUS = 0 # Nur benötigt für I2C Displays
#CIRCUITPY_FRAMEBUFFERIO = 0 # Nur benötigt für Framebuffer
CIRCUITPY_FONTIO = 0       # Nur benötigt für Fonts
#CIRCUITPY_CODEOP = 0       # Nur benötigt für codeop
#CIRCUITPY_JSON = 0         # Nur benötigt für JSON
#CIRCUITPY_OS = 0           # Nur benötigt für OS Funktionen
#CIRCUITPY_SELECT = 0       # Nur benötigt für select
#CIRCUITPY_STRUCT = 0       # Nur benötigt für struct
#CIRCUITPY_SYS = 0          # Nur benötigt für sys
#CIRCUITPY_TIME = 0         # Nur benötigt für time
#CIRCUITPY_VECTORIO = 0     # Nur benötigt für VectorIO
#CIRCUITPY_WARNINGS = 0     # Nur benötigt für warnings
#CIRCUITPY_ZLIB = 0         # Nur benötigt für zlib
#CIRCUITPY_AESIO = 0        # Nur benötigt für AES Verschlüsselung
#CIRCUITPY_BINASCII = 0     # Nur benötigt für binascii
#CIRCUITPY_BITMAPFILTER = 0 # Nur benötigt für Bitmap Filter
#CIRCUITPY_BITMAPTOOLS = 0  # Nur benötigt für Bitmap Tools
#CIRCUITPY_MSGPACK = 0      # Nur benötigt für MessagePack
#CIRCUITPY_RE = 0           # Nur benötigt für reguläre Ausdrücke
#CIRCUITPY_TERMINALIO = 0   # Nur benötigt für Terminal IO
CIRCUITPY_TOUCHIO = 0      # Nur benötigt für Touch IO
#CIRCUITPY_ULAB_CDC = 0     # Nur benötigt für CDC ulab
CIRCUITPY_USB_MIDI = 0     # Nur benötigt für USB MIDI
#CIRCUITPY_COUNTIO = 0      # Nur benötigt für countio
#CIRCUITPY_DIGITALIO = 0    # Wird bereits durch KEYPAD benötigt?
#CIRCUITPY_EEEPROOM = 0     # Wird EEPROM benötigt?
CIRCUITPY_EPAPERDISPLAY = 0 # Wird ein ePaper Display verwendet?
#CIRCUITPY_FOURWIRE = 0     # Wird Fourwire verwendet?
#CIRCUITPY_GETPASS = 0      # Wird getpass verwendet?
#CIRCUITPY_GIFIO = 0        # Wird GIFIO verwendet?
#CIRCUITPY_JPEGIO = 0       # Wird JPEGIO verwendet?
#CIRCUITPY_KEYPAD_DEMUX = 0    # Wird keypad_demux verwendet?
#CIRCUITPY_KEYPAD_KEYMATRIX = 0 # Wird eine Keymatrix verwendet?
#CIRCUITPY_KEYPAD_KEYS = 0      # Werden Keys verwendet?
#CIRCUITPY_KEYPAD_SHIFTREGISTERKEYS = 0   # Werden ShiftRegisterKeys verwendet?
#CIRCUITPY_LOCALE = 0       # Wird locale verwendet?
#CIRCUITPY_MEMORYMAP = 0    # Wird memorymap verwendet?
#CIRCUITPY_MICROCONTROLLER = 0 # Wird microcontroller verwendet?
#CIRCUITPY_NEOPIXEL_WRITE = 0 # Wird neopixel_write verwendet?
#CIRCUITPY_NVM = 0          # Wird NVM verwendet?
#CIRCUITPY_RAINBOWIO = 0    # Wird rainbowio verwendet?
#CIRCUITPY_RANDOM = 0       # Wird random verwendet?
#CIRCUITPY_RTC = 0          # Wird rtc verwendet?
#CIRCUITPY_SDCARDIO = 0     # Wird sdcardio verwendet?
#CIRCUITPY_STORAGE = 0      # Wird storage verwendet?
#CIRCUITPY_SYNTHIO = 0      # Wird synthio verwendet?
